package org.healthnlp.deepphe.summarization.drools.rules;

//list any import classes here.
import org.healthnlp.deepphe.summarization.drools.kb.*;
import org.healthnlp.deepphe.summarization.drools.kb.impl.*;

// ============================================================
//  
// Tumor Size
//
// Set 1: Document Genre Rules for sourcing data
//
// ============================================================

rule "002_breastCancerTumorSize Tumor Size From First Reliable Encounter"
	salience 1000
	when
	    $g : KbGoal (name == "extract-tumor-size",
                isActive > 0)
        KbEncounter ($encounterOneId : id,
                     $encounterOneSequence : sequence)
        $t : TumorSize (summarizableId == $encounterOneId)
        KbPatient( $patientId : id ) 
        not
        	TumorSize (summarizableId == $patientId)  
    then
        TumorSize patientTumorSize = beanCopyTumorSize($t);
        patientTumorSize.setSummarizableId($patientId);
 	    insert(patientTumorSize);
 	    System.out.println("<DROOLS-ENGINE> Nominalized tumor size as " + patientTumorSize.getClass().getSimpleName());
    end

rule "002_breastCancerTumorSize Transition Goal State"
	salience 500
	when
	    $g : KbGoal (name == "extract-tumor-size",
                isActive > 0)
    then

    	retract($g);
    	System.out.println("<DROOLS-ENGINE> Achieved goal " + $g.getName());
    end
    
function TumorSize beanCopyTumorSize(TumorSize tumorSize) {
        return (TumorSize) beanCopy(tumorSize);
        }    
