package org.healthnlp.deepphe.summarization.drools.rules;

//list any import classes here.
import org.healthnlp.deepphe.summarization.drools.kb.*;
import org.healthnlp.deepphe.summarization.drools.kb.impl.*;


rule "002_breastCancerTumorSize Transition Goal State"
	salience 500
	when
	    $g : KbGoal (name == "extract-tumor-size",
                isActive > 0)
    then
    	System.out.println("<DROOLS-ENGINE> Achieved goal " + $g.getName());
    	retract($g);
    end
