// ER – other encounter 	
//
// If patient has encounter data "primary tumor" from Other Report
// with ER relation <ER, value1> AFTER encounter data from "primary tumor"
// from Pathology Report with ER relation <ER, value2> AND <ER, value1> = <ER, value2>
// => add reference to phenotype ER = value 
//
	
// PR – other encounter
//	
// If patient has encounter data “primary tumor” from Other Report with ER relation
// <PR, value1> AFTER encounter data from “primary tumor” from Pathology Report
// with PR relation <PR, value2> AND <PR, value1> = <PR, value2>
//
 	
// Her2 – other encounter 	
//
// If patient has encounter data “primary tumor” from Other Report 
// with HER2 relation < HER2, value1> AFTER encounter data from “primary tumor” 
// from Pathology Report with HER2 relation 
// < HER2, value2> AND < HER2, value1> = < HER2, value2> 
	
// ER – other encounter discrepent 	
//
// If patient has encounter data “primary tumor” from Other Report with 
// ER relation <ER, value1> AFTER encounter data from “primary tumor” 
// from Pathology Report with ER AND <ER, value1> NOT = <ER, value2>relation <ER, value2> => 
// Then what? Perhaps flag this in some way as discrepent? Send to classifier? 
// Get Human Review? 
// Ask the Stuctured Data? 
// Other ideas? 	

// PR – other encounter discrepent 
//	
// If patient has encounter data “primary tumor” from Other Report
// with PR relation < PR, value1> 
// AFTER encounter data from “primary tumor” from Pathology Report
// with PR relation < PR, value2> AND < PR, value1> NOT = < PR, value2> => 
// Then what? Perhaps flag this in some way as discrepent? Send to classifier? 
// Get Human Review? Ask the Stuctured Data? Other ideas? 	

// HER2 – other encounter discrepent
//
// If patient has encounter data “primary tumor” from 
// Other Report with Her2 relation < Her2, value1> AFTER encounter data from “primary tumor”
// from Pathology Report with Her2 relation < Her2, value2> AND < Her2, value1> NOT = < Her2, value2> => 
// Then what? Perhaps flag this in some way as discrepent? Send to classifier? Get Human Review?
// Ask the Stuctured Data? Other ideas? 	
// Her2/Neu phenotype preferentially obtained from Pathology Report 	
// In the absence of explicit interpretation statement: IHC 3+ or greater is positive,
// IHC 0 or 1+ is negative, IHC 2+ is equivocal 	
// Value from FISH or CISH takes precedence over IHC except when
// IHC is done after an equivocal FISH test

 